---
version: "3"
services:
  oxidized:
    restart: always
    image: oxidized/oxidized:0.29.1-30-g52c1f98
#    ports:
#      - 8081:8888/tcp
    environment:
      # time to update config from tracked devices (in seconds)
      CONFIG_RELOAD_INTERVAL: 3600
    volumes:
      - ./config/oxidized:/home/oxidized/.config/oxidized
  nginx:
    restart: always
    image: nginx:mainline-alpine3.18-slim
    ports:
      - 8080:8080/tcp
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d 
      - type: bind
        source: ./config/nginx/.htpasswd
        target: /etc/nginx/.htpasswd
        read_only: true
